### ISSUE TITLE
[BUG]: Not getting network bandwidth in my mac m1 air

### ISSUE THREAD

**Issue by shubhamku044** [2KAbhishek/tmux2k#1]
### Description of the bug

![image](https://user-images.githubusercontent.com/77788249/227734585-9cbd0b7f-5501-43db-b151-35bb119aed41.png)
I used your plugin but not getting network-bandwidth

### Steps To Reproduce

1. Just add the plugin to `.tmux.conf`
2. launch the tmux

**Comment by 2KAbhishek** [comment]
I have not tested out the bandwidth functionality on Mac you can try making modifications to https://github.com/2KAbhishek/tmux2k/blob/main/scripts/network_bandwidth.sh file.

For reference you can try checking https://github.com/dracula/tmux/pull/113/ which has related code.

**Comment by shubhamku044** [comment]
I am working on the issue, I found the problem that these directory does not present in the mac.
![Screenshot 2023-03-29 at 2 03 23 AM](https://user-images.githubusercontent.com/77788249/228360237-eea321e5-2a82-449e-a879-83a822b4d5d3.jpg)

**Comment by 2KAbhishek** [comment]
The PR I suggested has some info you can use, and yes mac os won't have those files, you need to use something like this: https://github.com/dracula/tmux/pull/113/files#diff-0b9fe961926104b9378454226626affc13b34631388d0348f5df263f5739d8caR7-R19

**Comment by shubhamku044** [comment]
okay, I will check

**Comment by shubhamku044** [comment]
yes, I am trying to do the same, facing some issues while getting `*_bps`. I am debugging that issue as well.

![image](https://user-images.githubusercontent.com/77788249/228367802-62b7c2d0-4289-4465-9c4d-78f721f7a9bb.png)

**Comment by shubhamku044** [comment]
bro, I made it working 🎉
