### ISSUE TITLE
[BUG]: Theme not working properly in macOS

### ISSUE THREAD

**Issue by nizarcan** [2KAbhishek/tmux2k#12]
### Description of the bug

Hey, first of all, thanks for this great project, it looks really cool and promising! Overall theme does not fit the ones in the readme. Tried with a fresh install and still got this issue. This is what it looks like when cattpuccin is enabled without any customization:
![Screenshot 2024-03-27 at 17 47 15](https://github.com/2KAbhishek/tmux2k/assets/53255039/2f526898-b428-4473-9d5b-9a825b9050f0)

Using macOS 14.4 - Alacritty - tmux 3.4 - JetbrainsMono Nerd Font and tried other terminal emulators and they also behave similarly

### Steps To Reproduce

1. Install tmux
2. Set tmux config as below:
```
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin '2kabhishek/tmux2k'
set -g mouse on
set -g default-terminal "screen-256color"

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 

unbind Up     
unbind Down   
unbind Left   
unbind Right

set -g @tmux2k-theme 'catppuccin'

run '~/.tmux/plugins/tpm/tpm'
```
3. Restart tmux

**Comment by mikecbone** [comment]
I have the same issue, the status bar changes layout and has the defined plugins like cpu, network, time etc but it doesn't have the theme styling. 

- Macbook Pro M3 Max
- Mac OS 14.3.1
- iTerm2 3.4.23
- Byobu 6.12
- tmux 3.4
- tmuxinator 3.1.2
- MesloLGS NF Font


~/.tmux.conf:
```bash
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin '2kabhishek/tmux2k'

# tmux2k settings
set @tmux2k-theme 'default'
set -g @tmux2k-military-time true

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

~/.byobu/profile.tmux:
```bash
source $BYOBU_PREFIX/share/byobu/profiles/tmux

set -g mouse on
```

**Comment by 2KAbhishek** [comment]
@mikecbone can you share a screenshot here

**Comment by chiumichael** [comment]
Encountering the same issue here

<img width="1672" alt="Screenshot 2024-03-29 at 7 13 37 PM" src="https://github.com/2KAbhishek/tmux2k/assets/5535024/2ad7358b-d7a1-4058-8496-553aeab1cb95">

**Comment by nizarcan** [comment]
> I tested this on mac, and it seems to be working fine, I'll recommend uninstalling the extension and reinstalling

As I stated in the description, even with fresh install the error persists. Since others are also having the exact same issue with mine, maybe there's a dependency that is on your machine that we don't have in our systems?

**Comment by 2KAbhishek** [comment]
Let me investigate this, thanks for the information guys 

I'll post my findings here

**Comment by 2KAbhishek** [comment]
Figured it out!

macOS comes with a fairly older version of bash, which does not support all of the scripting shenanigans happening for the colors to work.

To fix it install bash from brew and restart tmux

```bash
brew install bash
```

This should solve the problem :)

**Comment by 2KAbhishek** [comment]
FYI @chiumichael @mikecbone @nizarcan

Let me know if you still face any issues after this, I will close the issue for now

**Comment by julienandreu** [comment]
I'm using zsh and face the same bug, do you have a workaround for me?
