### ISSUE TITLE
[BUG]: incomplete status report

### ISSUE THREAD

**Issue by jbutcher93** [2KAbhishek/tmux2k#16]
### Description of the bug

Status items are not being reported correctly, or at all, in the bar, but if I run the scripts directly I receive the appropriate values. No ram % and I am not in fact `Offline`

<img width="1136" alt="Screenshot 2024-05-27 at 1 45 19 AM" src="https://github.com/2KAbhishek/tmux2k/assets/95865907/624af1ee-b6ec-41f8-8a14-db57b76a25a7">

`ram.sh` for example:
<img width="71" alt="Screenshot 2024-05-27 at 1 46 53 AM" src="https://github.com/2KAbhishek/tmux2k/assets/95865907/9498efb5-f914-49fa-8745-8a75989cf41a">

### Steps To Reproduce

1. I have tmux installed through `brew`
2. Manually installed tpm
3. Installed the theme. See `.tmux.conf` below

```bash
set-environment -g PATH "/opt/homebrew/bin:/bin:/usr/bin"
set-option -g default-terminal "screen-256color"
set-option -g default-shell "/bin/bash"
unbind C-b
set -g prefix C-space
bind C-space send-prefix

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin '2kabhishek/tmux2k'
set -g @tmux2k-theme 'onedark'
set -g @tmux2k-icons-only true
set -g @tmux2k-start-icon window
set -g @tmux2k-compact-windows true
set -g @tmux2k-cpu-display-load true

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

**Comment by 2KAbhishek** [comment]
Can you share some more details about the environment, your os, hardware etc

The more context the better 

Also you can take a look at the scripts for ram and network to tweak it for your system, PRs always welcome
