### ISSUE TITLE
[ENH]: Is there a way to get the window list aligned to the left?

### ISSUE THREAD

**Issue by nickythorne** [2KAbhishek/tmux2k#19]
### Description

Is there a way to configure the window list to be left aligned, in the case where there are no left icons configured? 

Currently running into an overlapping issue that would be mitigated if we had the option to decide how the window list was aligned.

**Comment by 2KAbhishek** [comment]
@nickythorne thanks for opening up the issue, its been addressed here:
https://github.com/2KAbhishek/tmux2k/releases/tag/1.1

Cheers :)
