### ISSUE TITLE
[BUG]: Git Lock

### ISSUE THREAD

**Issue by paradigm-lab** [2KAbhishek/tmux2k#6]
### Description of the bug

As I am working within a VCS (Git) I mostly get locks

### Steps To Reproduce

Commits, Rebase, I mostly get the git locks

### Additional Information
I can't say that its actual bug but let have the less calls to reduce the number of locks and to make it more efficient because I have to repeat the same thing when I get a lock

_No response_

**Comment by paradigm-lab** [comment]
> ### Description of the bug
> 
> As I am working within a VCS (Git) I mostly get locks
> ### Steps To Reproduce
> 
> Commits, Rebase, I mostly get the git locks
> ### Additional Information
> I can't say that its actual bug but let have the less calls to reduce the number of locks and to make it more efficient because I have to repeat the same thing when I get a lock
> 
> _No response_

**Comment by 2KAbhishek** [comment]
I haven't seen this issue occurring with my daily usage, you may want to look at other git processes running
